# Generated by Django 5.0.6 on 2024-06-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(default='', upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
