# Generated by Django 5.0.6 on 2024-06-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_pelicula_duracion_pelicula_portada_pelicula_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
